### ISSUE TITLE
Cannot install concrete-ml==1.0.0, ...

### ISSUE THREAD

**Issue by MikeHatchi** [zama-ai/concrete-ml#79]
Goal: install concrete-ml

Context
MacOS 10.14
Intel
python --version 3.8.2

Steps:
inside a virtual environment handled by conda

Just run ```pip install concrete-ml```

Bug:

<details>
<p>

```
ERROR: Cannot install concrete-ml==1.0.0, concrete-ml==1.0.1, concrete-ml==1.0.2 and concrete-ml==1.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    concrete-ml 1.0.3 depends on concrete-python==1.0.0
    concrete-ml 1.0.2 depends on concrete-python==1.0.0
    concrete-ml 1.0.1 depends on concrete-python==1.0.0
    concrete-ml 1.0.0 depends on concrete-python==1.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

</p>
</details>

Then, if you try to ```pip install concrete-python``` or with ```pip install concrete-python==1.0.0```

<details>
<p>

```
ERROR: Could not find a version that satisfies the requirement concrete-python (from versions: none)
ERROR: No matching distribution found for concrete-python
```

</p>
or
<p>

```
ERROR: Could not find a version that satisfies the requirement concrete-python==1.0.0 (from versions: none)
ERROR: No matching distribution found for concrete-python==1.0.0
```

</p>
</details>

Thus, if you try another logic: ```pip install concrete-ml==1.0.3```

<details>
<p>

```
Collecting concrete-ml==1.0.3
  Using cached concrete_ml-1.0.3-py3-none-any.whl (178 kB)
Collecting boto3<2.0.0,>=1.23.5 (from concrete-ml==1.0.3)
  Using cached boto3-1.26.145-py3-none-any.whl (135 kB)
Requirement already satisfied: brevitas==0.8.0 in /Users/mike/anaconda3/envs/fhe_chess/lib/python3.8/site-packages (from concrete-ml==1.0.3) (0.8.0)
INFO: pip is looking at multiple versions of concrete-ml to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement concrete-python==1.0.0 (from concrete-ml) (from versions: none)
ERROR: No matching distribution found for concrete-python==1.0.0
```

</p>
</details>

**Comment by aquint-zama** [comment]
I think the issue comes from concrete-python installation, could you check this post and test the suggested commands: https://community.zama.ai/t/troubleshooting-concrete-installation-on-apple-silicon/577

**Comment by MikeHatchi** [comment]
@aquint-zama thx and Hi.

Everything was in order:
- python version correct : 3.8
- pip version correct : >23
- python architecture : Mach-O 64-bit executable x86_64 as it is an Intel

```
pip freeze | grep concrete
```
Doesn't print anything

**Comment by MikeHatchi** [comment]
well, I've create a new env with python 3.10

```
(mlfhe) VRONA-MBP:~ mike$ pip install concrete-ml
Collecting concrete-ml
  Using cached concrete_ml-1.0.3-py3-none-any.whl (178 kB)
Collecting skops==0.5.0
  Downloading skops-0.5.0-py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.8/92.8 kB 1.2 MB/s eta 0:00:00
Collecting onnx==1.13.1
  Downloading onnx-1.13.1-cp310-cp310-macosx_10_12_x86_64.whl (12.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 1.7 MB/s eta 0:00:00
Collecting hummingbird-ml[onnx]==0.4.8
  Using cached hummingbird_ml-0.4.8-py2.py3-none-any.whl (164 kB)
Collecting skorch==0.11.0
  Using cached skorch-0.11.0-py3-none-any.whl (155 kB)
Collecting scipy==1.10.1
  Downloading scipy-1.10.1-cp310-cp310-macosx_10_9_x86_64.whl (35.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.1/35.1 MB 1.7 MB/s eta 0:00:00
Collecting uvicorn<0.22.0,>=0.21.0
  Downloading uvicorn-0.21.1-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 kB 963.3 kB/s eta 0:00:00
Collecting protobuf==3.20.3
  Downloading protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.1/162.1 kB 1.1 MB/s eta 0:00:00
Collecting typing-extensions==4.4.0
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting setuptools==65.6.3
  Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
Collecting python-multipart<0.0.7,>=0.0.6
  Downloading python_multipart-0.0.6-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 735.4 kB/s eta 0:00:00
Collecting fastapi<0.94.0,>=0.93.0
  Downloading fastapi-0.93.0-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 956.4 kB/s eta 0:00:00
Collecting onnxoptimizer==0.3.10
  Using cached onnxoptimizer-0.3.10.tar.gz (18.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/cm/79mndh7174jf8l2sy41z6r_80000gn/T/pip-install-h7yjiuha/onnxoptimizer_8327acea7d73406f9b3ae630eb462092/setup.py", line 76, in <module>
          assert CMAKE, 'Could not find "cmake" executable!'
      AssertionError: Could not find "cmake" executable!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I did try with ```pip3```as well.

**Comment by MikeHatchi** [comment]
same issue under python 3.9
concerning concrete-python, perhaps another of installation through downloading the package directly from the repo could help.

to sum up: under my configuration, within a new venv it is not possible.

**Comment by MikeHatchi** [comment]
same issue under python 3.9
concerning concrete-python, perhaps another of installation through downloading the package directly from the repo could help.

**Comment by aquint-zama** [comment]
> AssertionError: Could not find "cmake" executable!

I think your issue is with onnxoptimizer that require cmake, could you try to install it and then reinstall concrete-ml with `brew install cmake` (if you are using Homebrew)

**Comment by aquint-zama** [comment]
The issue was linked to macOs version, concrete-ml and concrete-python requires macOs 11 or later
